subjects = [
    "Accounting",
    "Aerospace Studies",
    "Afro-American Studies",
    "Animal Science",
    "Anthropology",
    "Arabic",
    "Architecture",
    "Architecture and Design",
    "Art",
    "Art - Student Teaching",
    "Art History",
    "Arts Extension",
    "Asian Studies",
    "Astronomy",
    "Bachelor’s Deg. W/Indiv Conc.",
    "Biochemistry And Molecular Bio.",
    "Biology",
    "Biostatistics",
    "Biostats & Epidemiology",
    "Biotechnology",
    "Building & Construction Tech",
    "Catalan",
    "Chemical Engineering",
    "Chemistry",
    "Chinese",
    "Civil & Environmental Engrg",
    "Classics",
    "College of Inform & Comp Sci",
    "Communication",
    "Communication Disorders",
    "Community Health (see PUBHLTH)",
    "Comparative Literature",
    "Computer Science",
    "Dance",
    "Dutch",
    "Economics",
    "Education",
    "Electrical & Computer Engin",
    "Engineering",
    "English",
    "English Writing Program",
    "English as a Second language",
    "Entomology",
    "Environmental Conservation",
    "Environmental Design",
    "Environmental Health Sciences",
    "Environmental Science",
    "Epidemiology",
    "Exchange",
    "Faculty First Year Seminars",
    "Film Studies",
    "Finance",
    "Finance and Operations Mgt",
    "Finnish",
    "Five Coll Ctr: World Languages",
    "Food Science",
    "French Studies",
    "French-Student Teaching",
    "Geography",
    "Geology",
    "Geosciences",
    "German",
    "Graduate School",
    "Greek",
    "Haitian Creole",
    "Health Promotion & Policy",
    "Hebrew",
    "Heritage Studies",
    "Hispanic Lit. & Linguistics",
    "History",
    "Honors College",
    "Hospitality & Tourism Managmnt",
    "Human Development",
    "Humanities and Fine Arts",
    "Informatics",
    "Information Security",
    "Interpreter’s Studies",
    "Isenberg School of Management",
    "Italian Studies",
    "Italian-Student Teaching",
    "Japanese",
    "Journalism",
    "Judaic Studies",
    "Kinesiology",
    "Korean",
    "LL: Acting",
    "LL: Art & Photography",
    "LL: Arts Management",
    "LL: Business & Financial Plan",
    "LL: Career & Personal Develpmt",
    "LL: Computers",
    "LL: Donahue Leadership Prog",
    "LL: English as a 2nd Language",
    "LL: Food and Drink",
    "LL: Global Asset & Risk Mgmt",
    "LL: Health & Fitness",
    "LL: Languages",
    "LL: License Renewal",
    "LL: Music",
    "LL: Parks & Conservation Law",
    "LL: Personal Awareness",
    "LL: Real Estate",
    "LL: Soils/Plants/Insects",
    "LL: Special Interest",
    "LL: Sports"",Recrtn & Outdoors",
    "LL: Study Skills & Test Taking",
    "LL: Sustainability/Green",
    "LL: Wind Energy",
    "LL: Wood Identification",
    "LL: Writing"", Literature &Drama",
    "Labor Studies",
    "Landscape Architecture",
    "Landscape Contracting",
    "Languages"", Literature&Culture",
    "Latin",
    "Latin American Studies",
    "Latin-Student Teaching",
    "Legal Studies",
    "Linguistics",
    "Management",
    "Marketing",
    "Mathematics",
    "Mechanical & Industrial Engrg",
    "Microbiology",
    "Middle Eastern Studies",
    "Military Leadership",
    "Modern European Studies",
    "Molecular & Cellular Biology",
    "Music",
    "Music Education",
    "Music"", Applied",
    "National Student Exchange",
    "Natural Resources Conservation",
    "Natural Sciences",
    "Neuroscience & Behavior",
    "Nursing",
    "Nutrition",
    "Operations & Info Management",
    "Organismic & Evolutionary Biol",
    "Philosophy",
    "Physics",
    "Plant Biology",
    "Polish",
    "Political Science",
    "Polymer Science & Engineering",
    "Portuguese",
    "Portuguese-Student Teaching",
    "Psychology & Brain Sciences",
    "Public Health",
    "Public Policy & Administration",
    "Regional Planning",
    "Resource Economics",
    "Romanian",
    "Russian",
    "Scandinavian",
    "School Psychology",
    "Service Learning",
    "Slavic",
    "Slavic & E European Studies",
    "Social & Behavioral Science",
    "Social Thought & Polic. Econ",
    "Sociology",
    "Spanish",
    "Spanish - Student Teaching",
    "Sport Management",
    "Statistics",
    "Stockbridge Sch of Agriculture",
    "Sustainable Community",
    "Swedish",
    "Theater",
    "UMass Graduate Course Exchange",
    "UMass Practicum",
    "Univ Interdepartmental Course",
    "University Without Walls",
    "Women"",Gender"",Sexuality Studies",
    "Worcester Nursing Program",
    "Yiddish"
]
